version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - redis_net

volumes:
  redis_data:

networks:
  redis_net:
